name: Node.js Package

on:
  release:
    types:
      - created

jobs:
  publish:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        dirName: ['hls.js']

    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          use-policy-store: true
          egress-policy: audit
          api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@adrise'

      - run: npm set-script prepare ""

      - run: npm install ci --legacy-peer-deps

      - run: npm run build

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
